Search.appendIndex(
    [
                {
            "fqsen": "\\loadUsers\u0028\u0029",
            "name": "loadUsers",
            "summary": "Na\u010Dten\u00ED\u0020u\u017Eivatel\u016F\u0020ze\u0020souboru",
            "url": "namespaces/default.html#function_loadUsers"
        },                {
            "fqsen": "\\saveUsers\u0028\u0029",
            "name": "saveUsers",
            "summary": "ulo\u017Een\u00ED\u0020u\u017Eivatel\u016F\u0020do\u0020souboru",
            "url": "namespaces/default.html#function_saveUsers"
        },                {
            "fqsen": "\\listUsers\u0028\u0029",
            "name": "listUsers",
            "summary": "Vr\u00E1t\u00ED\u0020seznam\u0020u\u017Eivatel\u016F",
            "url": "namespaces/default.html#function_listUsers"
        },                {
            "fqsen": "\\getUser\u0028\u0029",
            "name": "getUser",
            "summary": "Vyhled\u00E1n\u00ED\u0020u\u017Eivatele\u0020podle\u0020ID",
            "url": "namespaces/default.html#function_getUser"
        },                {
            "fqsen": "\\addUser\u0028\u0029",
            "name": "addUser",
            "summary": "P\u0159id\u00E1n\u00ED\u0020nov\u00E9ho\u0020u\u017Eivatele\u0020do\u0020datab\u00E1ze\nHeslo\u0020je\u0020p\u0159ed\u0020ulo\u017Een\u00EDm\u0020zahashov\u00E1no",
            "url": "namespaces/default.html#function_addUser"
        },                {
            "fqsen": "\\deleteProfilePicture\u0028\u0029",
            "name": "deleteProfilePicture",
            "summary": "Smaz\u00E1n\u00ED\u0020profilov\u00E9ho\u0020obr\u00E1zku\u0020u\u017Eivatele",
            "url": "namespaces/default.html#function_deleteProfilePicture"
        },                {
            "fqsen": "\\deleteUser\u0028\u0029",
            "name": "deleteUser",
            "summary": "Smaz\u00E1n\u00ED\u0020u\u017Eivatele",
            "url": "namespaces/default.html#function_deleteUser"
        },                {
            "fqsen": "\\saveReservations\u0028\u0029",
            "name": "saveReservations",
            "summary": "Ulo\u017Een\u00ED\u0020rezervac\u00ED\u0020do\u0020souboru",
            "url": "namespaces/default.html#function_saveReservations"
        },                {
            "fqsen": "\\deleteReservation\u0028\u0029",
            "name": "deleteReservation",
            "summary": "Smaz\u00E1n\u00ED\u0020rezervace",
            "url": "namespaces/default.html#function_deleteReservation"
        },                {
            "fqsen": "\\editReservation\u0028\u0029",
            "name": "editReservation",
            "summary": "\u00DAprava\u0020rezervace",
            "url": "namespaces/default.html#function_editReservation"
        },                {
            "fqsen": "\\editUser\u0028\u0029",
            "name": "editUser",
            "summary": "Editace\u0020u\u017Eivatele",
            "url": "namespaces/default.html#function_editUser"
        },                {
            "fqsen": "\\handleFileUpload\u0028\u0029",
            "name": "handleFileUpload",
            "summary": "Handle\u0020file\u0020upload",
            "url": "namespaces/default.html#function_handleFileUpload"
        },                {
            "fqsen": "\\getDataById\u0028\u0029",
            "name": "getDataById",
            "summary": "Na\u010Dten\u00ED\u0020u\u017Eivatel\u016F\u0020ze\u0020souboru",
            "url": "namespaces/default.html#function_getDataById"
        },                {
            "fqsen": "\\saveDataToJsonFile\u0028\u0029",
            "name": "saveDataToJsonFile",
            "summary": "Ulo\u017Een\u00ED\u0020dat\u0020do\u0020souboru\u0020JSON",
            "url": "namespaces/default.html#function_saveDataToJsonFile"
        },                {
            "fqsen": "\\loadReservations\u0028\u0029",
            "name": "loadReservations",
            "summary": "Funkce\u0020pro\u0020na\u010Dten\u00ED\u0020rezervac\u00ED\u0020z\u0020JSON\u0020souboru",
            "url": "namespaces/default.html#function_loadReservations"
        },                {
            "fqsen": "\\getUserReservations\u0028\u0029",
            "name": "getUserReservations",
            "summary": "Funkce\u0020pro\u0020na\u010Dten\u00ED\u0020u\u017Eivatel\u016F\u0020z\u0020JSON\u0020souboru",
            "url": "namespaces/default.html#function_getUserReservations"
        },                {
            "fqsen": "\\check_collision\u0028\u0029",
            "name": "check_collision",
            "summary": "Reservation\u0020validation",
            "url": "namespaces/default.html#function_check_collision"
        },                {
            "fqsen": "\\check_quantity\u0028\u0029",
            "name": "check_quantity",
            "summary": "Check\u0020if\u0020the\u0020quantity\u0020is\u0020within\u0020the\u0020allowed\u0020range",
            "url": "namespaces/default.html#function_check_quantity"
        },                {
            "fqsen": "\\check_timeslot\u0028\u0029",
            "name": "check_timeslot",
            "summary": "Check\u0020if\u0020the\u0020timeslot\u0020is\u0020within\u0020the\u0020allowed\u0020range",
            "url": "namespaces/default.html#function_check_timeslot"
        },                {
            "fqsen": "\\handleEditReservation\u0028\u0029",
            "name": "handleEditReservation",
            "summary": "Handle\u0020the\u0020creation\u0020of\u0020a\u0020new\u0020reservation",
            "url": "namespaces/default.html#function_handleEditReservation"
        },                {
            "fqsen": "\\validateInputs\u0028\u0029",
            "name": "validateInputs",
            "summary": "Validate\u0020user\u0020input",
            "url": "namespaces/default.html#function_validateInputs"
        },                {
            "fqsen": "\\validateName\u0028\u0029",
            "name": "validateName",
            "summary": "Validate\u0020user\u0020input\u0020for\u0020editing",
            "url": "namespaces/default.html#function_validateName"
        },                {
            "fqsen": "\\validateEmail\u0028\u0029",
            "name": "validateEmail",
            "summary": "Validate\u0020email",
            "url": "namespaces/default.html#function_validateEmail"
        },                {
            "fqsen": "\\check_email\u0028\u0029",
            "name": "check_email",
            "summary": "Check\u0020if\u0020the\u0020email\u0020already\u0020exists",
            "url": "namespaces/default.html#function_check_email"
        },                {
            "fqsen": "\\validatePhone\u0028\u0029",
            "name": "validatePhone",
            "summary": "Validate\u0020phone\u0020number",
            "url": "namespaces/default.html#function_validatePhone"
        },                {
            "fqsen": "\\validatePassword\u0028\u0029",
            "name": "validatePassword",
            "summary": "Validate\u0020password",
            "url": "namespaces/default.html#function_validatePassword"
        },                {
            "fqsen": "\\validate_current_password\u0028\u0029",
            "name": "validate_current_password",
            "summary": "Validate\u0020current\u0020password",
            "url": "namespaces/default.html#function_validate_current_password"
        },                {
            "fqsen": "\\doesIDExist\u0028\u0029",
            "name": "doesIDExist",
            "summary": "Check\u0020if\u0020the\u0020ID\u0020exists",
            "url": "namespaces/default.html#function_doesIDExist"
        },                {
            "fqsen": "\\validateAgreement\u0028\u0029",
            "name": "validateAgreement",
            "summary": "Validate\u0020agreement",
            "url": "namespaces/default.html#function_validateAgreement"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
